# Introduction {#intro}

The supplementary material to the  *Chrysopsis highlandsensis* dataset from Archbold Biological Station.

The GIS and Data Management program at [Archbold Biological Station](https://www.archbold-station.org/gis-and-data-mgmt/) maintains a comprehensive collection of ecological and environmental data gathered through various research initiatives and ongoing long-term monitoring projects. One key platform for accessing this data is the Archbold Biological Station' [Ecological Data Inventory (EDI)](https://portal.edirepository.org/nis/home.jsp), which hosts extensive datasets related to biodiversity, land cover, climate, and ecological patterns.

From source we gathered the following information:

1. Data were collected from 1999-2025 from 11 subpopulations at three properties – Archbold, Highlands Hammock State Park, and the Lake Wales Ridge State Forest.
2. From 1999-2022, censusing was conducted quarterly in March, June, September, and December, and only in December beginning in 2023. All demographic data were collected in December, and only survival and recruitment were recorded in the other censuses. 
3. Data were collected from permanent quadrats or transects. The dimensions can be found in the provided excel worksheet under ‘plot_data’.
4. The species might respond to fire and disturbance. Dates of prescribed burns, hurricanes, and mechanical treatment should be considered when analyzing these data.


## Setup

We use the following packages: `tidyverse`, `patchwork`, `skimr`, `ipmr`, `binom`, `bbmle`, `gridExtra`, `lme4`, `GGally`, `viridis`, `scales`

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# Packages
packages <- c('patchwork', 'skimr', 'ipmr', 'binom', 'bbmle', 
              'gridExtra', 'lme4', 'GGally', 'viridis', 'scales', 'MASS',
              'lubridate', 'tidyverse', 'mgcv')
lapply(packages, library, character.only = TRUE)


# Specification 
# Define head-directory 
v_head <- c('archbold')
# Define species
v_species <- c('Chrysopsis highlandsensis')
# Customized delimiter for `read_delim` function, comma is predefined
custom_delimiter <- c()


# Create a unique species abbreviation for file naming
v_sp_abb  <- tolower(
  gsub(' ', '', paste(
    substr(unlist(strsplit(v_species, ' ')), 1, 2), collapse = '')))

# Define script prefix
v_script_prefix <- str_c(v_head)

# Plot subtitle
v_ggp_suffix    <- paste(
  tools::toTitleCase(v_head), '-', v_species)


# Models
v_mod_set_gr <- c()
v_mod_set_su <- c()
v_mod_set_fl <- c()


# Directory 
dir_wd     <- file.path('C:', 'code', 'RUPDemo_IPMs')
dir_pub    <- file.path(dir_wd, paste0(v_head))
dir_R      <- file.path(dir_pub, 'R',       v_sp_abb)
dir_data   <- file.path(dir_pub, 'data',    v_sp_abb)
dir_result <- file.path(dir_pub, 'results', v_sp_abb)
dir_func   <- file.path(dir_wd, 'helper_functions')


# Functions
# plot your survival data 'binned' (instead of 'jittered')
source(file.path(dir_func, 'plot_binned_prop.R'))
# 
source(file.path(dir_func, 'line_color_pred_fun.R'))
# 
source(file.path(dir_func, 'predictor_fun.R'))
```

