# Models {#models}

For this IPM we will model the following processes:

1. Survival                  | fire
2. Growth                    | fire
3. Flowering probability     | fire
4. Flower number conditional | fire
5. Recruits                  | fire

## Survival

```{r 4 survival}
# Survival data ----------------------------------------------------------------
df_su <- df %>%
  filter(!is.na(survives), size_t0 != 0, !is.na(fire)) %>%
  dplyr::select(site, plant_id, year, size_t0, survives, size_t1,
         logsize_t0, logsize_t1, logsize_t0_2, logsize_t0_3, fire)


# Survival plotting
df_su_binned <- df_su %>%
  group_split(fire) %>%
  purrr::map_df(~ plot_binned_prop(.x, 10, logsize_t0, survives) %>%
                  mutate(fire = unique(.x$fire)))

fig_su_overall <- ggplot(df_su_binned, aes(x = logsize_t0, y = survives, color = fire)) +
  geom_jitter(data = df_su, aes(x = logsize_t0, y = survives, color = fire),
              position = position_jitter(width = 0.1, height = 0.3), alpha = 0.1) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = lwr, ymax = upr), width = 0.2, linewidth = 0.5) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  theme(
    axis.text = element_text(size = 8),
    title = element_text(size = 10),
    plot.subtitle = element_text(size = 8),
    legend.title = element_blank(),
    legend.position = 'top') +
  labs(
    title = 'Survival',
    subtitle = v_ggp_suffix,
    x = expression('log(size)'[t0]),
    y = 'Survival Probability')

fig_su_overall


# Survival models --------------------------------------------------------------
mod_su_0 <- glm(survives ~ fire, data = df_su, family = 'binomial') 
mod_su_1 <- glm(survives ~ logsize_t0 + fire, data = df_su, family = 'binomial') 
mod_su_2 <- glm(survives ~ logsize_t0 + logsize_t0_2 + fire, data = df_su, family = 'binomial')  
mod_su_3 <- glm(survives ~ logsize_t0 + logsize_t0_2 + logsize_t0_3 + fire, data = df_su, family = 'binomial')  

# Compare models using AIC
mods_su      <- list(mod_su_0, mod_su_1, mod_su_2, mod_su_3)
mods_su_dAIC <- AICctab(mods_su, weights = T, sort = F)$dAIC

# Get the sorted indices of dAIC values
mods_su_sorted <- order(mods_su_dAIC)

# Establish the index of model complexity
if (length(v_mod_set_su) == 0) {
  mod_su_index_bestfit <- mods_su_sorted[1]
  v_mod_su_index       <- mod_su_index_bestfit - 1 
} else {
  mod_su_index_bestfit <- v_mod_set_su +1
  v_mod_su_index       <- v_mod_set_su
}

mod_su_bestfit <- mods_su[[mod_su_index_bestfit]]
mod_su_ranef   <- coef(mod_su_bestfit)


# Prediction 
df_su_pred <- data.frame(
  logsize_t0   = rep(seq(min(df_su$logsize_t0), max(df_su$logsize_t0), length.out = 100), 2),
  logsize_t0_2 = rep(seq(min(df_su$logsize_t0_2), max(df_su$logsize_t0_2), length.out = 100), 2),
  fire = rep(c('No fire', 'Fire'), each = 100)) %>%
  mutate(
    fire = factor(fire, levels = c('No fire', 'Fire')),
    survives = predict(mod_su_bestfit, newdata = ., type = 'response'))


# Binned data
df_su_binned <- bind_rows(
  plot_binned_prop(filter(df_su, fire == 'No fire'), 10, logsize_t0, survives) %>%
    mutate(fire = 'No fire'),
  plot_binned_prop(filter(df_su, fire == 'Fire'), 10, logsize_t0, survives) %>%
    mutate(fire = 'Fire'))


# Survival plot ----------------------------------------------------------------
# Plot 1
fig_su_line_combined <- ggplot() +
  geom_jitter(data = df_su, aes(x = logsize_t0, y = survives, color = fire),
              alpha = 0.25, width = 0.08, height = 0.3) +
  geom_line(data = df_su_pred, aes(x = logsize_t0, y = survives, color = fire),
            linewidth = 0.9) +  
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  labs(title = NULL, x = 'Size at time t0 (log())', y = 'Survival to time t1') +
  theme(legend.position = 'none')

# Plot 2 
fig_su_bin_combined <- ggplot() +
  geom_point(data = df_su_binned, aes(x = logsize_t0, y = survives, color = fire)) +
  geom_errorbar(data = df_su_binned, aes(x = logsize_t0, ymin = lwr, ymax = upr, color = fire),
                width = 0.2) +
  geom_line(data = df_su_pred, aes(x = logsize_t0, y = survives, color = fire),
            linewidth = 0.9) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  ylim(0, 1) +
  labs(title = NULL, x = 'Size at time t0 (log())', y = 'Survival to time t1') +
  theme(legend.title = element_blank(), legend.position = 'top')

# Combine
fig_su_all <- fig_su_line_combined + fig_su_bin_combined +
  plot_annotation(
    title = 'Survival',
    subtitle = v_ggp_suffix,
    theme = theme(
      plot.title = element_text(size = 14, face = 'bold'),
      plot.subtitle = element_text(size = 10, face = 'italic')))

fig_su_all
```



## Growth
```{r}
# Growth data ------------------------------------------------------------------
df_gr <- df %>%
  filter(size_t0 != 0,
         !is.na(size_t1),
         size_t1 > 0,
         !is.na(fire)) %>%
  mutate(
    logsize_t0   = log(size_t0),
    logsize_t1   = log(size_t1),
    logsize_t0_2 = logsize_t0^2,
    logsize_t0_3 = logsize_t0^3) %>%
  dplyr::select(plant_id, year, size_t0, size_t1,
         logsize_t0, logsize_t1, logsize_t0_2, logsize_t0_3,
         fire)

fig_gr_overall <- ggplot(df_gr, aes(x = logsize_t0, y = logsize_t1, color = fire)) +
  geom_point(alpha = 0.5, size = 0.7) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  theme(
    axis.text       = element_text(size = 8),
    title           = element_text(size = 10),
    plot.subtitle   = element_text(size = 8),
    legend.title    = element_blank(),
    legend.position = 'top') +
  labs(
    title    = 'Growth',
    subtitle = v_ggp_suffix,
    x        = expression('log(size)'[t0]),
    y        = expression('log(size)'[t1]))

fig_gr_overall


# Growth model -----------------------------------------------------------------
mod_gr_0 <- lm(logsize_t1 ~ fire, data = df_gr)

mod_gr_1 <- lm(logsize_t1 ~ logsize_t0 + fire, data = df_gr)

mod_gr_2 <- lm(logsize_t1 ~ logsize_t0 + logsize_t0_2 + fire, data = df_gr)

mod_gr_3 <- lm(logsize_t1 ~ logsize_t0 + logsize_t0_2 + logsize_t0_3 + fire, 
               data = df_gr)

mods_gr      <- list(mod_gr_0, mod_gr_1, mod_gr_2, mod_gr_3)
mods_gr_dAIC <- AICctab(mods_gr, weights = TRUE, sort = FALSE)$dAIC
mods_gr_sorted <- order(mods_gr_dAIC)

if (length(v_mod_set_gr) == 0) {
  mod_gr_index_bestfit <- mods_gr_sorted[1]
  v_mod_gr_index       <- mod_gr_index_bestfit - 1 
} else {
  mod_gr_index_bestfit <- v_mod_set_gr + 1
  v_mod_gr_index       <- v_mod_set_gr
}

mod_gr_bestfit <- mods_gr[[mod_gr_index_bestfit]]
mod_gr_ranef   <- coef(mod_gr_bestfit)


# Prediction 
df_gr_pred <- data.frame(
  logsize_t0 = rep(
    seq(min(df_gr$logsize_t0, na.rm = TRUE),
        max(df_gr$logsize_t0, na.rm = TRUE), length.out = 100), 2),
  fire = rep(c('No fire', 'Fire'), each = 100)) %>%
  mutate(
    fire = factor(fire, levels = c('No fire', 'Fire')),
    logsize_t0_2 = logsize_t0^2,
    logsize_t0_3 = logsize_t0^3)

df_gr_pred$logsize_t1 <- predict(mod_gr_bestfit, newdata = df_gr_pred)


# Growth plots ----------------------------------------------------------------- 
# Plot 1: Observed points + prediction lines
fig_gr_line_combined <- ggplot(df_gr, aes(x = logsize_t0, y = logsize_t1, color = fire)) +
  geom_point(alpha = 0.4, size = 0.8) +
  geom_line(data = df_gr_pred, aes(x = logsize_t0, y = logsize_t1, color = fire),
            linewidth = 1) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  labs(x = expression('log(size)'[t0]),
       y = expression('log(size)'[t1])) +
  theme(
    legend.position = 'top',
    legend.title = element_blank(),
    plot.title = element_blank(),
    plot.subtitle = element_blank())

# Plot 2: Predicted vs observed
fig_gr_pred_combined <- ggplot(df_gr, aes(x = predict(mod_gr_bestfit, newdata = df_gr),
                                          y = logsize_t1, color = fire)) +
  geom_point(alpha = 0.4, size = 0.8) +
  geom_abline(intercept = 0, slope = 1, color = 'black',
              linetype = 'dashed', linewidth = 1) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  labs(x = 'Predicted', y = 'Observed') +
  theme(
    legend.position = 'top',
    legend.title = element_blank(),
    plot.title = element_blank(),
    plot.subtitle = element_blank())

# Combine plots
fig_gr_all_combined <- fig_gr_line_combined + fig_gr_pred_combined +
  plot_annotation(
    title = 'Growth Prediction',
    subtitle = v_ggp_suffix,
    theme = theme(
      plot.title = element_text(size = 14, face = 'bold'),
      plot.subtitle = element_text(size = 10, face = 'italic')))

fig_gr_all_combined
```

### Growth variance

```{r}
# Growth variance --------------------------------------------------------------
# Fitted values from growth model
mod_gr_x   <- fitted(mod_gr_bestfit)  
# Squared residuals
mod_gr_y   <- resid(mod_gr_bestfit)^2  
# Non-linear model for variance
mod_gr_var <- nls(
  mod_gr_y ~ a * exp(b * mod_gr_x), start = list(a = 1, b = 0),
  control = nls.control(maxiter = 1000, tol = 1e-6, warnOnly = TRUE)) 

```


## Flowering
### Flowering probability
```{r}

# Flowering data ----------------------------------------------------------------
df_fl <- df %>%
  filter(!is.na(flower),
         !is.na(fire),
         !is.na(size_t0),
         !is.na(survives)) %>%
  dplyr::select(plant_id, year, size_t0, size_t1, flower, fl_nr, 
         logsize_t0, logsize_t1, logsize_t0_2, logsize_t0_3, fire)

# Create binned flowering probability by fire group
df_fl_binned <- df_fl %>%
  group_split(fire) %>%
  map_df(~ plot_binned_prop(.x, 10, logsize_t0, flower) %>%
           mutate(fire = unique(.x$fire)))

# Plot overlapped flowering probability
fig_fl_overall <- ggplot(df_fl_binned, aes(x = logsize_t0, y = flower, color = fire)) +
  geom_jitter(
    data = df_fl,
    aes(x = logsize_t0, y = flower, color = fire),
    position = position_jitter(width = 0.1, height = 0.3),
    alpha = 0.1) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = lwr, ymax = upr), width = 0.2, linewidth = 0.5) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  theme(
    axis.text = element_text(size = 8),
    title = element_text(size = 10),
    plot.subtitle = element_text(size = 8),
    legend.title = element_blank(),
    legend.position = 'top') +
  labs(
    title = 'Flowering probability by fire status',
    subtitle = v_ggp_suffix,
    x = expression('log(size)'[t0]),
    y = 'Flowering Probability')

fig_fl_overall


# Flower model -----------------------------------------------------------------
mod_fl_0 <- glm(flower ~ fire, data = df_fl, family = 'binomial') 

mod_fl_1 <- glm(flower ~ logsize_t0 + fire, data = df_fl, family = 'binomial') 

mod_fl_2 <- glm(flower ~ logsize_t0 + logsize_t0_2 + fire,
                data = df_fl, family = 'binomial')  

mod_fl_3 <- glm(flower ~ logsize_t0 + logsize_t0_2 + logsize_t0_3 + fire,
                data = df_fl, family = 'binomial')  

mods_fl      <- list(mod_fl_0, mod_fl_1, mod_fl_2, mod_fl_3)
mods_fl_dAIC <- AICctab(mods_fl, weights = TRUE, sort = FALSE)$dAIC
mods_fl_sorted <- order(mods_fl_dAIC)

if (length(v_mod_set_fl) == 0) {
  mod_fl_index_bestfit <- mods_fl_sorted[1]
  v_mod_fl_index       <- mod_fl_index_bestfit - 1 
} else {
  mod_fl_index_bestfit <- v_mod_set_fl + 1
  v_mod_fl_index       <- v_mod_set_fl
}

mod_fl_bestfit <- mods_fl[[mod_fl_index_bestfit]]
mod_fl_ranef   <- coef(mod_fl_bestfit)


# Prediction
df_fl_pred <- data.frame(
  logsize_t0 = rep(seq(min(df_fl$logsize_t0, na.rm = TRUE),
                       max(df_fl$logsize_t0, na.rm = TRUE), length.out = 100), 2),
  fire = rep(c('No fire', 'Fire'), each = 100)) %>%
  mutate(
    fire = factor(fire, levels = c('No fire', 'Fire')),
    logsize_t0_2 = logsize_t0^2,
    logsize_t0_3 = logsize_t0^3)

df_fl_pred$flower <- predict(mod_fl_bestfit, newdata = df_fl_pred, type = 'response')


# Binned observed data for both fire levels
df_fl_binned <- bind_rows(
  plot_binned_prop(filter(df_fl, fire == 'No fire'), 10, logsize_t0, flower) %>%
    mutate(fire = 'No fire'),
  plot_binned_prop(filter(df_fl, fire == 'Fire'), 10, logsize_t0, flower) %>%
    mutate(fire = 'Fire'))


# Flower plots -----------------------------------------------------------------
# Plot 1: Raw jitter + prediction lines
fig_fl_line_combined <- ggplot() +
  geom_jitter(data = df_fl, aes(x = logsize_t0, y = flower, color = fire),
              alpha = 0.25, width = 0.08, height = 0.3) +
  geom_line(data = df_fl_pred, aes(x = logsize_t0, y = flower, color = fire),
            linewidth = 0.9) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  labs(title = NULL, x = 'Size at time t0 (log())', y = 'Flowering Probability') +
  theme(legend.position = 'none')


# Plot 2: Binned + prediction
fig_fl_bin_combined <- ggplot() +
  geom_point(data = df_fl_binned, aes(x = logsize_t0, y = flower, color = fire)) +
  geom_errorbar(data = df_fl_binned, aes(x = logsize_t0, ymin = lwr, ymax = upr, color = fire),
                width = 0.2) +
  geom_line(data = df_fl_pred, aes(x = logsize_t0, y = flower, color = fire),
            linewidth = 0.9) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  ylim(0, 1) +
  labs(title = NULL, x = 'Size at time t0 (log())', y = 'Flowering Probability') +
  theme(legend.title = element_blank(), legend.position = 'top')


# Combine
fig_fl_all <- fig_fl_line_combined + fig_fl_bin_combined +
  plot_annotation(
    title = 'Flowering',
    subtitle = v_ggp_suffix,
    theme = theme(
      plot.title = element_text(size = 14, face = 'bold'),
      plot.subtitle = element_text(size = 10, face = 'italic')))

fig_fl_all

```

### Number of flowers conditional on flowering
```{r}

# Number of flowers conditional on flowering -----------------------------------
df_fl_cond <- df_fl %>%
  filter(flower == 1) %>%
  filter(fl_nr %% 1 == 0)

# Models INCLUDING fire
mod_fl_n_0 <- glm.nb(fl_nr ~ fire, data = df_fl_cond)

mod_fl_n_1 <- glm.nb(fl_nr ~ logsize_t0 + fire,
                     data = df_fl_cond)

mod_fl_n_2 <- glm.nb(fl_nr ~ logsize_t0 + logsize_t0_2 + fire,
                     data = df_fl_cond)

mod_fl_n_3 <- glm.nb(fl_nr ~ logsize_t0 + logsize_t0_2 + logsize_t0_3 + fire,
                     data = df_fl_cond)

# Model dplyr::selection
mods_fl_n <- list(mod_fl_n_0, mod_fl_n_1, mod_fl_n_2, mod_fl_n_3)

mods_fl_n_dAIC <- AICctab(mods_fl_n, weights = TRUE, sort = FALSE)$dAIC
mods_fl_n_sorted <- order(mods_fl_n_dAIC)

mod_fl_n_bestfit <- mods_fl_n[[mods_fl_n_sorted[1]]]
v_mod_fl_n_index <- mods_fl_n_sorted[1] - 1


# Predictions for flower number -----------------------------------------------
# Create prediction grid
df_fl_n_pred <- expand.grid(
  logsize_t0 = seq(min(df_fl_cond$logsize_t0),
                   max(df_fl_cond$logsize_t0),
                   length.out = 100),
  fire = c('No fire', 'Fire'))

# Ensure correct factor structure
df_fl_n_pred <- df_fl_n_pred %>%
  mutate(
    fire = factor(fire, levels = levels(df_fl_cond$fire)),
    logsize_t0_2 = logsize_t0^2,
    logsize_t0_3 = logsize_t0^3)

# Predict
df_fl_n_pred$fl_nr <- predict(mod_fl_n_bestfit,
                              newdata = df_fl_n_pred,
                              type = 'response')


# Binned observed data (manual binning) ----------------------------------------

df_fl_n_binned <- df_fl_cond %>%
  mutate(bin = cut(logsize_t0, breaks = 10)) %>%
  group_by(fire, bin) %>%
  summarise(
    logsize_t0 = mean(logsize_t0, na.rm = TRUE),
    fl_nr = mean(fl_nr, na.rm = TRUE),
    se = sd(fl_nr, na.rm = TRUE) / sqrt(n()),
    .groups = 'drop') %>%
  mutate(
    lwr = fl_nr - 1.96 * se,
    upr = fl_nr + 1.96 * se )


# Flower number plots ----------------------------------------------------------

# Plot 1: Raw jitter + prediction lines
fig_fl_n_line_combined <- ggplot() +
  geom_jitter(data = df_fl_cond,
              aes(x = logsize_t0, y = fl_nr, color = fire),
              alpha = 0.25, width = 0.08, height = 0.3) +
  geom_line(data = df_fl_n_pred,
            aes(x = logsize_t0, y = fl_nr, color = fire),
            linewidth = 0.9) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  labs(title = NULL,
       x = 'Size at time t0 (log())',
       y = 'Number of flowers') +
  theme(legend.position = 'none')


# Plot 2: Binned + prediction
fig_fl_n_bin_combined <- ggplot() +
  geom_point(data = df_fl_n_binned,
             aes(x = logsize_t0, y = fl_nr, color = fire)) +
  geom_errorbar(data = df_fl_n_binned,
                aes(x = logsize_t0, ymin = lwr, ymax = upr, color = fire),
                width = 0.2) +
  geom_line(data = df_fl_n_pred,
            aes(x = logsize_t0, y = fl_nr, color = fire),
            linewidth = 0.9) +
  scale_color_manual(values = c('No fire' = 'black', 'Fire' = 'red')) +
  theme_bw() +
  labs(title = NULL,
       x = 'Size at time t0 (log())',
       y = 'Number of flowers') +
  theme(legend.title = element_blank(),
        legend.position = 'top')


# Combine
fig_fl_n_all <- fig_fl_n_line_combined + fig_fl_n_bin_combined +
  plot_annotation(
    title = 'Flower number',
    subtitle = v_ggp_suffix,
    theme = theme(
      plot.title = element_text(size = 14, face = 'bold'),
      plot.subtitle = element_text(size = 10, face = 'italic'))
  )

fig_fl_n_all
```

## Recruitment
```{r}

# Recruitment ------------------------------------------------------------------
df_re <- df %>%
  group_by(year, site) %>%
  summarise(
    fire = if_else(any(fire == 'Fire', na.rm = TRUE), 'Fire', 'No fire'),
    tot_p_area = sum(size_t0, na.rm = TRUE),
    .groups = 'drop') %>%
  {
    df_quad <- .
    
    df_group <- df_quad %>%
      group_by(year) %>%
      summarise(g_cov = mean(tot_p_area), .groups = 'drop')
    
    df_cover <- left_join(df_quad, df_group, by = 'year') %>%
      mutate(year = as.integer(year + 1)) %>%
      drop_na()
    
    df_recruit <- df %>%
      group_by(year, site) %>%
      summarise(nr_quad = sum(recruit, na.rm = TRUE), .groups = 'drop')
    
    left_join(df_cover, df_recruit, by = c('year', 'site'))
  } %>%
  mutate(fire = factor(fire, levels = c('No fire', 'Fire')))

# Plot: recruitment vs parent area
ggplot(df_re, aes(x = tot_p_area, y = nr_quad, colour = fire)) + 
  geom_point(alpha = 0.5, pch = 16, size = 1) +  
  theme_bw() + 
  labs(title    = 'Recruitment',
       subtitle = v_ggp_suffix,
       x        = expression('Total parent plant area '[t0]),   
       y        = expression('Number of recruits '     [t1])) +
  theme(plot.subtitle = element_text(size = 8))

```


### Per capita reproduction

```{r}
# Recruitment model ------------------------------------------------------------
df_re_mod <- df_re %>% filter(!is.na(nr_quad))
# Fit a negative binomial model for recruitment
mod_rec <- MASS::glm.nb(nr_quad ~ fire, data = df_re_mod)

# Generate predictions for recruitment
df_re_mod <- df_re_mod %>% 
  mutate(mod_pred = predict(mod_rec, type = 'response')) 


# Per-capita reproduction ------------------------------------------------------
df_repr_pc <- df %>%
  filter(!is.na(size_t0)) %>% 
  summarize(n_adults = n()) %>%
  bind_cols(
    df_re_mod %>%
      summarize(nr_quad = sum(nr_quad, na.rm = TRUE),
                mod_pred = sum(mod_pred, na.rm = TRUE))) %>%
  mutate(
    repr_pc_mean = mod_pred / n_adults,
    repr_pc_obs = nr_quad / n_adults) %>%
  drop_na()

# overall level
df %>% 
  filter(!is.na(size_t0)) %>% 
  summarize(n_adults = n()) %>% 
  bind_cols(df %>% 
              filter(!is.na(recruit)) %>%
              summarize(n_rec = n())) %>% 
  mutate(rp_pc_m = n_rec / n_adults)


# site level
df %>% 
  filter(!is.na(size_t0)) %>%
  group_by(site) %>% 
  summarize(n_adults = n()) %>% 
  left_join(df %>% 
              filter(!is.na(recruit)) %>%
              group_by(site) %>%
              summarize(n_rec = n()),
            by = 'site') %>% 
  mutate(n_rec = ifelse(is.na(n_rec), 0, n_rec)) %>%
  mutate(repr_pc_mean = n_rec / n_adults) %>% 
  summarise(n_adults = sum(n_adults),
            n_rec    = sum(n_rec),
            rp_pc_m  = mean(repr_pc_mean))
```

### Flower to recruits transition
```{r}
# Recruits per flower ----------------------------------------------------------
df_fl_by_year <- df %>%
  filter(!is.na(fl_nr)) %>%
  group_by(year) %>%
  summarise(total_flowers = sum(fl_nr, na.rm = TRUE)) %>%
  mutate(year = year + 1)

df_rec_by_year <- df %>%
  filter(recruit == 1) %>%
  group_by(year) %>%
  summarise(n_recruits = n())

df_rep_fl_ratio <- df_fl_by_year %>%
  left_join(df_rec_by_year, by = 'year') %>%
  mutate(recruits_per_flower = n_recruits / total_flowers)

repr_flower_mean   <- mean(df_rep_fl_ratio$recruits_per_flower, na.rm = TRUE)
repr_flower_median <- median(df_rep_fl_ratio$recruits_per_flower, na.rm = TRUE)
repr_flower_median
```

